/**
 * Global site + theme configuration.
 * Edit values here to rebrand the theme. All values are typed and consumed
 * across layouts, components, RSS, sitemap, and SEO.
 */

export type Locale = 'en' | 'fr';

export interface SiteConfig {
  /** Public URL of the deployed site, no trailing slash. */
  url: string;
  /** Default site title used as homepage <title> and meta. */
  title: string;
  /** Site tagline / description. */
  description: string;
  /** Author/handle shown in footer + meta. */
  author: {
    name: string;
    url?: string;
    avatar?: string;
    bio?: string;
  };
  /** Default OG image relative to /public. */
  defaultOgImage: string;
  /** Default locale. EN, served at root with no prefix. */
  defaultLocale: Locale;
  /** Supported locales. */
  locales: readonly Locale[];
  /** Number of posts per page on listings. */
  postsPerPage: number;
  /** Display ISO 8601 date format if true, otherwise locale-aware. */
  isoDates: boolean;
}

export interface NavItem {
  /** Unique key matching i18n.ts entries. */
  key: string;
  /** Path WITHOUT leading locale prefix. The renderer adds it. */
  href: string;
  /** Optional icon name (e.g. "home", "tags"). */
  icon?: string;
}

export interface SocialLink {
  label: string;
  href: string;
  icon: string;
}

export interface GiscusConfig {
  /** Master switch. */
  enabled: boolean;
  /** GitHub repo (e.g. `user/repo`). */
  repo: string;
  /** Repo ID (from giscus.app). */
  repoId: string;
  /** Discussion category. */
  category: string;
  /** Category ID. */
  categoryId: string;
  /** Discussion mapping strategy. */
  mapping: 'pathname' | 'url' | 'title' | 'og:title' | 'specific' | 'number';
  /** Strict matching. */
  strict: '0' | '1';
  /** Enable reactions on the main post. */
  reactionsEnabled: '0' | '1';
  /** Emit metadata events. */
  emitMetadata: '0' | '1';
  /** Comment input position. */
  inputPosition: 'top' | 'bottom';
  /** Lazy load. */
  loading: 'lazy' | 'eager';
}

export const SITE: SiteConfig = {
  url: import.meta.env.SITE_URL ?? 'https://chirping-astro.example.com',
  title: 'Chirping Astro',
  description:
    'A modern, multilingual Astro v6 theme inspired by Chirpy — built with Tailwind v4, daisyUI, MDX, Pagefind, and Giscus.',
  author: {
    name: 'Chirping Astro',
    url: 'https://github.com/your-handle',
    avatar: '/images/avatar.svg',
    bio: 'A staff engineer who writes about the web, type systems, and the joy of shipping.',
  },
  defaultOgImage: '/images/og-default.svg',
  defaultLocale: 'en',
  locales: ['en', 'fr'] as const,
  postsPerPage: 8,
  isoDates: false,
};

export const NAV: readonly NavItem[] = [
  { key: 'home', href: '/', icon: 'home' },
  { key: 'categories', href: '/categories', icon: 'stream' },
  { key: 'tags', href: '/tags', icon: 'tag' },
  { key: 'archives', href: '/archives', icon: 'archive' },
  { key: 'about', href: '/about', icon: 'info' },
] as const;

export const SOCIALS: readonly SocialLink[] = [
  { label: 'GitHub', href: 'https://github.com/your-handle', icon: 'github' },
  { label: 'Twitter', href: 'https://twitter.com/your-handle', icon: 'twitter' },
  { label: 'Email', href: 'mailto:hello@example.com', icon: 'envelope' },
  { label: 'RSS', href: '/rss.xml', icon: 'rss' },
] as const;

/**
 * Giscus comments. Set `enabled: false` to globally disable. Individual
 * posts may opt out via frontmatter `comments: false`.
 *
 * Generate values at https://giscus.app and either set them here or
 * (recommended) provide them via PUBLIC_GISCUS_* env vars at build time.
 */
export const GISCUS: GiscusConfig = {
  enabled: (import.meta.env.PUBLIC_GISCUS_ENABLED ?? 'false') === 'true',
  repo: import.meta.env.PUBLIC_GISCUS_REPO ?? '',
  repoId: import.meta.env.PUBLIC_GISCUS_REPO_ID ?? '',
  category: import.meta.env.PUBLIC_GISCUS_CATEGORY ?? 'Announcements',
  categoryId: import.meta.env.PUBLIC_GISCUS_CATEGORY_ID ?? '',
  mapping: 'pathname',
  strict: '0',
  reactionsEnabled: '1',
  emitMetadata: '0',
  inputPosition: 'bottom',
  loading: 'lazy',
};

/**
 * Pagefind runtime settings. The index itself is generated by `bun run pagefind`
 * after `astro build` and written to `dist/_pagefind/`.
 */
export const PAGEFIND = {
  /** Public path where the Pagefind bundle is served. */
  bundlePath: '/_pagefind/',
  /** Number of results to render per locale. */
  pageSize: 10,
} as const;
